### PR TITLE
Corrected structure to be more typical 

### PR DESCRIPTION
**Pull request by bheklilr**
Implementation for #1.

* I moved the code from `same_stats.py` to `samestats/samestats.py`
* Added `samestats/__init__.py`, `samestats/__main__.py`.
* Moved the datasets into a sub-module.
* Modified `load_dataset` to use `pkg_resources.resource_stream` to load these files from disk (tested, it works for me on Python 3.6.1 on Windows)
* Added `setup.py`, `setup.cfg` to describe the package.  The `setup.cfg` file will probably need more modifications in the future as we add more metadata.

Other changes in `samestats/samestats.py` are due to my editor automatically stripping trailing whitespace and me making a few minor modifications.

### CODE REVIEW

**Comment by bheklilr** [comment]
@jmatejka Ended up not getting time to work on it this weekend, had a surprise family gathering that ate up my free time.  Managed to get this one knocked out this morning though.

**Review by jmatejka — APPROVED** [review]
Nice, thanks!

I see in the 'setup.cfg' file it lists Python 3+, this was originally a 2.7 project, will be be able to make it work with both?

**Comment by bheklilr** [comment]
Could probably make it work with both without much issue.  I didn't test it with Python 2, but I didn't change anything that would affect the compatibility.  I just prefer not to support Python 2 anymore, but it's your project so you get to decide.

**Comment by jmatejka** [comment]
I think since this is such a small project, I'd prefer to support both if
we can.

**Pull request merged**
